// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAT")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("28d9b656-d3ab-4064-8409-9fe1833a80f2"),
                            CreatedAt = new DateTime(2025, 11, 15, 23, 10, 30, 797, DateTimeKind.Utc).AddTicks(2193),
                            Name = "Lenovo",
                            Price = 999.99m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 15, 23, 10, 30, 797, DateTimeKind.Utc).AddTicks(2197)
                        },
                        new
                        {
                            Id = new Guid("4b1056e5-040f-44f6-acdc-a778001759d6"),
                            CreatedAt = new DateTime(2025, 11, 15, 23, 10, 30, 797, DateTimeKind.Utc).AddTicks(2217),
                            Name = "Iphone 15",
                            Price = 800.77m,
                            StockQuantity = 10,
                            UpdatedAT = new DateTime(2025, 11, 15, 23, 10, 30, 797, DateTimeKind.Utc).AddTicks(2218)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
